/**
 * Authentication
 */
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const LOGIN_AS_GUEST = 'LOGIN_AS_GUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

/**
 * Babies
 */
export const GET_BABIES = 'GET_BABIES';
export const GET_BABIES_FAILED = 'GET_BABIES_FAILED';

/**
 * Activities
 */
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITIES_FAILED = 'GET_ACTIVITIES_FAILED';
export const START_ACTIVITY = 'START_ACTIVITY';
export const UPDATE_CURRENT_ACTIVITY = 'UPDATE_CURRENT_ACTIVITY';
export const UPDATE_CURRENT_ACTIVITIES = 'UPDATE_CURRENT_ACTIVITIES';